### ISSUE TITLE
Test script fails on vanilla clone

### ISSUE THREAD

**Issue by chris-kuhr** [awslabs/video-on-demand-on-aws-foundations#6]
If I clone the workflow and run the testscript I receive the following error message:
```
  console.log
    TypeError: Cannot read property '0' of undefined
        at Object.sendMetrics (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/lib/utils.js:193:28)
        at Object.<anonymous> (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/lib/utils.spec.js:180:17)
        at Object.asyncJestTest (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
        at /home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/queueRunner.js:75:41
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

      at Object.sendMetrics (lib/utils.js:232:17)

  console.log
    TypeError: Cannot read property '0' of undefined
        at Object.sendMetrics (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/lib/utils.js:193:28)
        at Object.<anonymous> (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/lib/utils.spec.js:184:17)
        at Object.asyncJestTest (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:106:37)
        at /home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/queueRunner.js:45:12
        at new Promise (<anonymous>)
        at mapper (/home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/queueRunner.js:28:19)
        at /home/christoph/Desktop/cf_vod_workflow.git/source/job-complete/node_modules/jest-jasmine2/build/queueRunner.js:75:41
        at processTicksAndRejections (internal/process/task_queues.js:93:5)

      at Object.sendMetrics (lib/utils.js:232:17)

```

Furthermore, regardless of what I do (I explicitly deleted job-settings.json) I always see the settings from that job-settings.json in the console output.

What is the problem here?

Best,
Ck

**Comment by morjoan** [comment]
Hi Ck, I'll try replicate the issue here at our end and see what might be happening. Will get back to you when we've got some findings. Thanks!

**Comment by chris-kuhr** [comment]
I figured out, that the json output I was seeing came from the unit test file.

**Comment by morjoan** [comment]
Hi Ck, 
Yes, we mock the job settings information that's fed to the test files. That's why deleting the job-settings.json has no effect. We are, however, missing some mocked metrics data which is why the sendMetrics test is spitting out the error you're seeing. Something we'll need to fix in the next release. Thanks for bringing it to our attention.
